### ISSUE TITLE
single file output

### ISSUE THREAD

**Issue by titaniumbones** [tscanlin/processmd#38]
Hello, I'm enjoying your tool very much, and find its flexibility a real pleasure. I'm a bit confused about how to generate a single json file from a directory.  So, for instance, if I have
```
|--Articles
    |--article1.md
    |--article2.md
```
I'd like to end up with just one json file that assembles all the individual objects into an array.  Is that something that can be done directly by the tool or would I have to walk through the files listed in summary.json and manually create the array?

**Comment by tscanlin** [comment]
Hey, thanks! Glad you are finding it useful.
Using the summary json file is the right way to go about this. Is there any reason the object with filenames as keys and the `sourceFileArray` doesn't work for you?

My intention of using an object rather than an array was to make lookups quicker as opposed to an array which you would need to iterate over.

Can you tell me a bit about your use case? I'm open to adding this as a feature / option. Also, you may be able to accomplish your desired output by processing with `jq` (https://stedolan.github.io/jq/)

**Comment by titaniumbones** [comment]
Hi @tscanlin ! 

The use case is maybe a little unusual. In a student demo during class, I am having students edit a group of markdown files in a github repo.  on merge, I'll have a gh action that generates a single json file from all the files.  In another location, I'll fetch the file and generate a set of components from the contents.  

So, the only product I'm really interested in is the final json file containing the full array of objects. Does that make sense? 

It may make more sense for me to just code up that part of the process myself, but I was hoping to keep things ultra-simple so that the repository is as clean as possible.

**Comment by tscanlin** [comment]
Does this PR help for your use case?
https://github.com/tscanlin/processmd/pull/39/files

**Comment by tscanlin** [comment]
This PR is published in `processmd@4.7.0`

Thanks for your suggestion / contribution to this project @titaniumbones. :)

Please encourage all of your students to contribute to open source projects! Even opening issues like this helps since someone else might want this too but may not be as vocal, and I'm happy to implement it especially if it's not too complicated to add and I know it's for a good cause. Good luck with your teaching!
